### ISSUE TITLE
Physical experiment

### ISSUE THREAD

**Issue by JiayunjieJYJ** [jimmyyhwu/spatial-intention-maps#1]
Hi, thanks a lot for the code! May I ask where can I buy the **physical robots** matching with this code , as shown in your physical experiment videos? 

Thank you very much!

**Comment by jimmyyhwu** [comment]
We purchased them on Amazon. It looks like they are still selling it right now: https://www.amazon.com/Vector-Robot-Anki-Hangs-Helps/dp/B07G3ZNK4Y

**Comment by JiayunjieJYJ** [comment]
OK! Thanks, I will try it.
