### ISSUE TITLE
Gets agent state

### ISSUE THREAD

**Issue by DosHacker** [jimmyyhwu/spatial-intention-maps#2]
Excuse me, I found in the code that when I get the agent state from the environment, I can only get the state of one agent at a time. Can I get the state of all agents at the same time?

**Comment by jimmyyhwu** [comment]
Yes, see example code here: https://github.com/jimmyyhwu/spatial-intention-maps/blob/master/tools_interactive_gui.py#L429

**Comment by DosHacker** [comment]
Okay, I got it. Thank you
